export const countries =[
    { "id": 1, "country": "Afghanistan", "tz": "Asia/Kabul", "locale_format": "fa-AF" },
    { "id": 2, "country": "Albania", "tz": "Europe/Tirane", "locale_format": "sq-AL" },
    { "id": 3, "country": "Algeria", "tz": "Africa/Algiers", "locale_format": "ar-DZ" },
    { "id": 4, "country": "Andorra", "tz": "Europe/Andorra", "locale_format": "ca-AD" },
    { "id": 5, "country": "Angola", "tz": "Africa/Luanda", "locale_format": "pt-AO" },
    { "id": 6, "country": "Antigua and Barbuda", "tz": "America/Antigua", "locale_format": "en-AG" },
    { "id": 7, "country": "Argentina", "tz": "America/Argentina/Buenos_Aires", "locale_format": "es-AR" },
    { "id": 8, "country": "Armenia", "tz": "Asia/Yerevan", "locale_format": "hy-AM" },
    { "id": 9, "country": "Australia", "tz": "Australia/Sydney", "locale_format": "en-AU" },
    { "id": 10, "country": "Austria", "tz": "Europe/Vienna", "locale_format": "de-AT" },
    { "id": 11, "country": "Azerbaijan", "tz": "Asia/Baku", "locale_format": "az-AZ" },
    { "id": 12, "country": "Bahamas", "tz": "America/Nassau", "locale_format": "en-BS" },
    { "id": 13, "country": "Bahrain", "tz": "Asia/Bahrain", "locale_format": "ar-BH" },
    { "id": 14, "country": "Bangladesh", "tz": "Asia/Dhaka", "locale_format": "bn-BD" },
    { "id": 15, "country": "Barbados", "tz": "America/Barbados", "locale_format": "en-BB" },
    { "id": 16, "country": "Belarus", "tz": "Europe/Minsk", "locale_format": "be-BY" },
    { "id": 17, "country": "Belgium", "tz": "Europe/Brussels", "locale_format": "nl-BE" },
    { "id": 18, "country": "Belize", "tz": "America/Belize", "locale_format": "en-BZ" },
    { "id": 19, "country": "Benin", "tz": "Africa/Porto-Novo", "locale_format": "fr-BJ" },
    { "id": 20, "country": "Bhutan", "tz": "Asia/Thimphu", "locale_format": "dz-BT" },
    { "id": 21, "country": "Bolivia", "tz": "America/La_Paz", "locale_format": "es-BO" },
    { "id": 22, "country": "Bosnia and Herzegovina", "tz": "Europe/Sarajevo", "locale_format": "bs-BA" },
    { "id": 23, "country": "Botswana", "tz": "Africa/Gaborone", "locale_format": "en-BW" },
    { "id": 24, "country": "Brazil", "tz": "America/Sao_Paulo", "locale_format": "pt-BR" },
    { "id": 25, "country": "Brunei", "tz": "Asia/Brunei", "locale_format": "ms-BN" },
    { "id": 26, "country": "Bulgaria", "tz": "Europe/Sofia", "locale_format": "bg-BG" },
    { "id": 27, "country": "Burkina Faso", "tz": "Africa/Ouagadougou", "locale_format": "fr-BF" },
    { "id": 28, "country": "Burundi", "tz": "Africa/Bujumbura", "locale_format": "fr-BI" },
    { "id": 29, "country": "Cabo Verde", "tz": "Atlantic/Cape_Verde", "locale_format": "pt-CV" },
    { "id": 30, "country": "Cambodia", "tz": "Asia/Phnom_Penh", "locale_format": "km-KH" },
    { "id": 31, "country": "Cameroon", "tz": "Africa/Douala", "locale_format": "fr-CM" },
    { "id": 32, "country": "Canada", "tz": "America/Toronto", "locale_format": "en-CA" },
    { "id": 33, "country": "Central African Republic", "tz": "Africa/Bangui", "locale_format": "fr-CF" },
    { "id": 34, "country": "Chad", "tz": "Africa/N'Djamena", "locale_format": "fr-TD" },
    { "id": 35, "country": "Chile", "tz": "America/Santiago", "locale_format": "es-CL" },
    { "id": 36, "country": "China", "tz": "Asia/Shanghai", "locale_format": "zh-CN" },
    { "id": 37, "country": "Colombia", "tz": "America/Bogota", "locale_format": "es-CO" },
    { "id": 38, "country": "Comoros", "tz": "Indian/Comoro", "locale_format": "ar-KM" },
    { "id": 39, "country": "Congo (Congo-Brazzaville)", "tz": "Africa/Brazzaville", "locale_format": "fr-CG" },
    { "id": 40, "country": "Congo (Congo-Kinshasa)", "tz": "Africa/Kinshasa", "locale_format": "fr-CD" },
    { "id": 41, "country": "Costa Rica", "tz": "America/Costa_Rica", "locale_format": "es-CR" },
    { "id": 42, "country": "Croatia", "tz": "Europe/Zagreb", "locale_format": "hr-HR" },
    { "id": 43, "country": "Cuba", "tz": "America/Havana", "locale_format": "es-CU" },
    { "id": 44, "country": "Cyprus", "tz": "Asia/Nicosia", "locale_format": "el-CY" },
    { "id": 45, "country": "Czech Republic", "tz": "Europe/Prague", "locale_format": "cs-CZ" },
    { "id": 46, "country": "Denmark", "tz": "Europe/Copenhagen", "locale_format": "da-DK" },
    { "id": 47, "country": "Djibouti", "tz": "Africa/Djibouti", "locale_format": "ar-DJ" },
    { "id": 48, "country": "Dominica", "tz": "America/Dominica", "locale_format": "en-DM" },
    { "id": 49, "country": "Dominican Republic", "tz": "America/Santo_Domingo", "locale_format": "es-DO" },
    { "id": 50, "country": "Ecuador", "tz": "America/Guayaquil", "locale_format": "es-EC" },
    { "id": 51, "country": "Egypt", "tz": "Africa/Cairo", "locale_format": "ar-EG" },
    { "id": 52, "country": "El Salvador", "tz": "America/El_Salvador", "locale_format": "es-SV" },
    { "id": 53, "country": "Equatorial Guinea", "tz": "Africa/Malabo", "locale_format": "es-GQ" },
    { "id": 54, "country": "Eritrea", "tz": "Africa/Asmara", "locale_format": "ti-ER" },
    { "id": 55, "country": "Estonia", "tz": "Europe/Tallinn", "locale_format": "et-EE" },
    { "id": 56, "country": "Eswatini", "tz": "Africa/Mbabane", "locale_format": "en-SZ" },
    { "id": 57, "country": "Ethiopia", "tz": "Africa/Addis_Ababa", "locale_format": "am-ET" },
    { "id": 58, "country": "Fiji", "tz": "Pacific/Fiji", "locale_format": "en-FJ" },
    { "id": 59, "country": "Finland", "tz": "Europe/Helsinki", "locale_format": "fi-FI" },
    { "id": 60, "country": "France", "tz": "Europe/Paris", "locale_format": "fr-FR" },
    { "id": 61, "country": "Gabon", "tz": "Africa/Libreville", "locale_format": "fr-GA" },
    { "id": 62, "country": "Gambia", "tz": "Africa/Banjul", "locale_format": "en-GM" },
    { "id": 63, "country": "Georgia", "tz": "Asia/Tbilisi", "locale_format": "ka-GE" },
    { "id": 64, "country": "Germany", "tz": "Europe/Berlin", "locale_format": "de-DE" },
    { "id": 65, "country": "Ghana", "tz": "Africa/Accra", "locale_format": "en-GH" },
    { "id": 66, "country": "Greece", "tz": "Europe/Athens", "locale_format": "el-GR" },
    { "id": 67, "country": "Grenada", "tz": "America/Grenada", "locale_format": "en-GD" },
    { "id": 68, "country": "Guatemala", "tz": "America/Guatemala", "locale_format": "es-GT" },
    { "id": 69, "country": "Guinea", "tz": "Africa/Conakry", "locale_format": "fr-GN" },
    { "id": 70, "country": "Guinea-Bissau", "tz": "Africa/Bissau", "locale_format": "pt-GW" },
    { "id": 71, "country": "Guyana", "tz": "America/Guyana", "locale_format": "en-GY" },
    { "id": 72, "country": "Haiti", "tz": "America/Port-au-Prince", "locale_format": "ht-HT" },
    { "id": 73, "country": "Honduras", "tz": "America/Tegucigalpa", "locale_format": "es-HN" },
    { "id": 74, "country": "Hungary", "tz": "Europe/Budapest", "locale_format": "hu-HU" },
    { "id": 75, "country": "Iceland", "tz": "Atlantic/Reykjavik", "locale_format": "is-IS" },
    { "id": 76, "country": "India", "tz": "Asia/Kolkata", "locale_format": "en-IN" },
    { "id": 77, "country": "Indonesia", "tz": "Asia/Jakarta", "locale_format": "id-ID" },
    { "id": 78, "country": "Iran", "tz": "Asia/Tehran", "locale_format": "fa-IR" },
    { "id": 79, "country": "Iraq", "tz": "Asia/Baghdad", "locale_format": "ar-IQ" },
    { "id": 80, "country": "Ireland", "tz": "Europe/Dublin", "locale_format": "en-IE" },
    { "id": 81, "country": "Israel", "tz": "Asia/Jerusalem", "locale_format": "he-IL" },
    { "id": 82, "country": "Italy", "tz": "Europe/Rome", "locale_format": "it-IT" },
    { "id": 83, "country": "Jamaica", "tz": "America/Jamaica", "locale_format": "en-JM" },
    { "id": 84, "country": "Japan", "tz": "Asia/Tokyo", "locale_format": "ja-JP" },
    { "id": 85, "country": "Jordan", "tz": "Asia/Amman", "locale_format": "ar-JO" },
    { "id": 86, "country": "Kazakhstan", "tz": "Asia/Almaty", "locale_format": "kk-KZ" },
    { "id": 87, "country": "Kenya", "tz": "Africa/Nairobi", "locale_format": "en-KE" },
    { "id": 88, "country": "Kiribati", "tz": "Pacific/Kiritimati", "locale_format": "en-KI" },
    { "id": 89, "country": "Korea (North)", "tz": "Asia/Pyongyang", "locale_format": "ko-KP" },
    { "id": 90, "country": "Korea (South)", "tz": "Asia/Seoul", "locale_format": "ko-KR" },
    { "id": 91, "country": "Kuwait", "tz": "Asia/Kuwait", "locale_format": "ar-KW" },
    { "id": 92, "country": "Kyrgyzstan", "tz": "Asia/Bishkek", "locale_format": "ky-KG" }
  ]